version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y python-dev
      - run:
          name: Install pyenv
          command: |
            curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
            cat \<<-'EOF' > /tmp/pyenv.sh
            export PYENV_ROOT="/home/circleci/.pyenv"
            export PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
            if [[ -d /home/circleci/venv ]]; then
                source /home/circleci/venv/bin/activate
            fi
            EOF
            sudo mv /tmp/pyenv.sh /etc/profile.d/
            bash -l -c "pyenv --version"
            bash -l -c "python -m venv ~/venv"
      - run:
          name: Install tox
          shell: /bin/bash -eo pipefail -l
          command: |
            pip install tox tox-pyenv
      - run:
          name: Run tests
          shell: /bin/bash -eo pipefail -l
          command: |
            tox

workflows:
  version: 2
  default-flow:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
